export enum ConfigVar {
  HOST = 'HOST',
  PORT = 'PORT',

  // Database
  MONGO_URI = 'MONGO_URI',

  // JWT
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',

  // Auth
  FACEBOOK_APP_ID = 'FACEBOOK_APP_ID',
  FACEBOOK_APP_SECRET = 'FACEBOOK_APP_SECRET',
  LINKEDIN_CLIENT_ID = 'LINKEDIN_CLIENT_ID',
  LINKEDIN_CLIENT_SECRET = 'LINKEDIN_CLIENT_SECRET',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
}
